_wandb:
    value:
        cli_version: 0.23.0
        e:
            tv28wcqtsavta66k9xe0agca42pgtj5s:
                args:
                    - --kl-weight
                    - "0.1"
                    - --ppo-clip
                    - "0.1"
                    - --lr
                    - "0.0001"
                    - --warmup-epochs
                    - "10"
                    - --rl-lr-scale
                    - "0.1"
                    - --num-epochs
                    - "20"
                    - --wandb-project
                    - ddmec-ablation-kl
                    - --wandb-name
                    - ablation_kl0.1_clip0.1_lr1e-04_20251129_212416
                codePath: run_ddmec.py
                codePathLocal: run_ddmec.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "341898686464"
                        used: "315700908032"
                email: adnankaremjs@gmail.com
                executable: C:\Users\dell\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe
                git:
                    commit: decd2f0c264484e9adea88d6db7e14246a1a3590
                    remote: https://github.com/adnankarim/ddpm-2d.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-52a0ace5-5c52-65b5-c262-b6023ee9285f
                host: DESKTOP-LITA292
                memory:
                    total: "34266128384"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\dell\Music\resd\run_ddmec.py
                python: CPython 3.12.10
                root: C:\Users\dell\Music\resd
                startedAt: "2025-11-29T20:24:21.671464Z"
                writerId: tv28wcqtsavta66k9xe0agca42pgtj5s
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.12.10
            "5": 0.23.0
            "8":
                - 3
            "10":
                - 21
            "12": 0.23.0
            "13": windows-amd64
architecture:
    value: DDMEC
batch_size:
    value: 64
dataset:
    value: 1D Gaussians
ddmec_total_params:
    value: 19522
ddmec_trainable_params:
    value: 19522
dist_1:
    value: N(2, 1)
dist_2:
    value: N(10, 1)
kl_weight:
    value: 0.1
learning_rate:
    value: 0.0001
model_1_total_params:
    value: 9761
model_1_trainable_params:
    value: 9761
model_2_total_params:
    value: 9761
model_2_trainable_params:
    value: 9761
num_epochs:
    value: 20
num_timesteps:
    value: 1000
num_train_samples:
    value: 100000
ppo_clip:
    value: 0.1
rl_lr_scale:
    value: 0.1
run_dir:
    value: runs\ablation_kl0.1_clip0.1_lr1e-04_20251129_212416_20251129_212420
warmup_epochs:
    value: 10
